name: deep_inside
description: A highly secure local storage solution for Flutter applications.
version: 1.0.0
homepage: https://github.com/username/deep_inside
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  crypto: ^3.0.0
  pointycastle: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  path_provider_platform_interface: ^2.1.0
  plugin_platform_interface: ^2.1.0
