name: deep_inside
description: A highly secure local storage solution for Flutter applications.
version: 0.0.2
homepage: https://github.com/MrShadowX00/deep_inside.git
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  crypto: ^3.0.6
  pointycastle: ^3.9.1
  flutter_lints: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  path_provider_platform_interface: ^2.1.0
  plugin_platform_interface: ^2.1.0
